# Generated by Django 2.1.5 on 2022-04-28 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('preview_link', models.URLField(verbose_name='Ссылка на превью')),
                ('initial_link', models.URLField(verbose_name='Основная ссылка')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.ManyToManyField(related_name='in_archive', to='logic.Article')),
                ('deleted', models.ManyToManyField(related_name='in_deleted', to='logic.Article')),
                ('reading_list', models.ManyToManyField(related_name='in_reading_list', to='logic.Article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
