# Generated by Django 3.1.7 on 2021-04-04 19:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='сuratorProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторы',
            },
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.CreateModel(
            name='PadawanProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=16, verbose_name='телефон')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('rank', models.CharField(choices=[('01', 'Рядовой соботыльник'), ('02', 'Младший сержант бота'), ('03', 'Сержант олимпиад'), ('04', 'Старшина перечней'), ('05', 'Товарищ прапорщик'), ('06', 'Старший соботыльник'), ('07', 'Лейтенант учёбы'), ('08', 'Капитан региона'), ('09', 'Майор тайм-менеджмента'), ('10', 'Полковник-бвишник'), ('11', 'Генерал всерос(с)а'), ('12', 'Магистр книг и пособий'), ('13', 'Повелитель бота'), ('14', 'Император всея Бота и Учёбы')], default='01', max_length=2, verbose_name='звание')),
                ('off_date', models.DateField(auto_now=True, verbose_name='окончание оплаченного периода')),
                ('weekend', models.CharField(choices=[('1', 'понедельник'), ('2', 'вторник'), ('3', 'среда'), ('4', 'четверг'), ('5', 'пятница'), ('6', 'суббота'), ('7', 'воскресенье')], default='7', max_length=1, verbose_name='выходной')),
                ('group', models.CharField(choices=[('P', 'Pro'), ('L', 'Lite')], default='L', max_length=1, verbose_name='группа')),
                ('utc', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(12)], verbose_name='временной сдвиг')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-20)], verbose_name='рейтинг')),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padawans', to='logic.curatorprofile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padawanProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подаван',
                'verbose_name_plural': 'Подваны',
                'ordering': ['-off_date'],
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='время')),
                ('activations', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='активации')),
                ('text', models.SlugField(verbose_name='текст')),
                ('users', models.ManyToManyField(blank=True, related_name='activatedCodes', to='logic.PadawanProfile')),
            ],
            options={
                'verbose_name': 'Код',
                'verbose_name_plural': 'Коды',
                'ordering': ['-days'],
            },
        ),
    ]
