# Generated by Django 3.1.7 on 2021-04-05 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20210404_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.IntegerField(null=True, verbose_name='id чата в телеге')),
                ('username', models.CharField(max_length=32, verbose_name='ник')),
                ('telephone', models.CharField(blank=True, max_length=16, verbose_name='телефон')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('rank', models.CharField(choices=[('01', 'Рядовой соботыльник'), ('02', 'Младший сержант бота'), ('03', 'Сержант олимпиад'), ('04', 'Старшина перечней'), ('05', 'Товарищ прапорщик'), ('06', 'Старший соботыльник'), ('07', 'Лейтенант учёбы'), ('08', 'Капитан региона'), ('09', 'Майор тайм-менеджмента'), ('10', 'Полковник-бвишник'), ('11', 'Генерал всерос(с)а'), ('12', 'Магистр книг и пособий'), ('13', 'Повелитель бота'), ('14', 'Император всея Бота и Учёбы')], default='01', max_length=2, verbose_name='звание')),
                ('off_date', models.DateField(auto_now=True, verbose_name='окончание оплаченного периода')),
                ('weekend', models.CharField(choices=[('1', 'понедельник'), ('2', 'вторник'), ('3', 'среда'), ('4', 'четверг'), ('5', 'пятница'), ('6', 'суббота'), ('7', 'воскресенье')], default='7', max_length=1, verbose_name='выходной')),
                ('group', models.CharField(choices=[('P', 'Pro'), ('L', 'Lite')], default='L', max_length=1, verbose_name='группа')),
                ('utc', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(12)], verbose_name='временной сдвиг')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-20)], verbose_name='рейтинг')),
            ],
            options={
                'verbose_name': 'Подаван',
                'verbose_name_plural': 'Подваны',
                'ordering': ['-off_date'],
            },
        ),
        migrations.AddField(
            model_name='curatorprofile',
            name='telegram',
            field=models.IntegerField(null=True, verbose_name='id чата в телеге'),
        ),
        migrations.AlterField(
            model_name='code',
            name='days',
            field=models.IntegerField(default=31, validators=[django.core.validators.MinValueValidator(0)], verbose_name='время'),
        ),
        migrations.DeleteModel(
            name='PadawanProfile',
        ),
        migrations.AddField(
            model_name='padawan',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padawans', to='logic.curatorprofile'),
        ),
        migrations.AlterField(
            model_name='code',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='codes', to='logic.Padawan'),
        ),
    ]
