# Generated by Django 3.1.7 on 2021-04-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20210405_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curatorprofile',
            old_name='telegram',
            new_name='chat_id',
        ),
        migrations.RenameField(
            model_name='padawan',
            old_name='telegram',
            new_name='chat_id',
        ),
    ]
