# Generated by Django 3.1.7 on 2021-04-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_auto_20210405_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatorprofile',
            name='chat_id',
            field=models.IntegerField(editable=False, null=True, verbose_name='id чата в телеге'),
        ),
        migrations.AlterField(
            model_name='padawan',
            name='chat_id',
            field=models.IntegerField(editable=False, null=True, verbose_name='id чата в телеге'),
        ),
    ]
