# Generated by Django 3.1.7 on 2021-04-05 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logic', '0005_auto_20210405_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.SlugField(verbose_name='описание')),
                ('end', models.DateTimeField(verbose_name='дата сдачи')),
                ('proof', models.ImageField(upload_to='', verbose_name='пруф')),
                ('padawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='logic.padawan')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(editable=False, null=True, verbose_name='id чата в телеге')),
                ('username', models.CharField(max_length=32, verbose_name='ник')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='сuratorProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторы',
            },
        ),
        migrations.AlterField(
            model_name='padawan',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padawans', to='logic.curator'),
        ),
        migrations.DeleteModel(
            name='CuratorProfile',
        ),
    ]
