# Generated by Django 3.1.7 on 2021-04-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_auto_20210405_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания задачи'),
        ),
        migrations.AlterField(
            model_name='padawan',
            name='off_date',
            field=models.DateField(auto_now_add=True, verbose_name='окончание оплаченного периода'),
        ),
        migrations.AlterField(
            model_name='task',
            name='proof',
            field=models.ImageField(null=True, upload_to='', verbose_name='пруф'),
        ),
    ]
